### Server Configuration ###
server:
  port: 8761

### Spring Configuration ###
spring:
  application:
    name: orchestrator

### Eureka Server Configuration ###
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  dashboard:
    showLastWillDiscoverySection: true