### Server Configuration ###
server:
  port: 8081

### Spring Configuration ###
spring:
  application:
    name: authenticator

### Eureka Server Configuration ###
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/