### Server Configuration ###
server:
  port: 8082

### Spring Configuration ###
spring:
  application:
    name: accountmanager

### Eureka Server Configuration ###
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/